CREATE USER IF NOT EXISTS 'aarr'@'%' IDENTIFIED BY 'aarr';
GRANT USAGE ON *.* TO 'aarr'@'%';
GRANT EXECUTE, SELECT, SHOW VIEW, ALTER, ALTER ROUTINE, CREATE, CREATE ROUTINE, CREATE TEMPORARY TABLES, CREATE VIEW, DELETE, DROP, EVENT, INDEX, INSERT, REFERENCES, TRIGGER, UPDATE, LOCK TABLES  ON `aarrstat`.* TO 'aarr'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;