CREATE USER IF NOT EXISTS 'aarr'@'localhost' IDENTIFIED BY 'aarr';
GRANT USAGE ON *.* TO 'aarr'@'localhost';
GRANT EXECUTE, SELECT, SHOW VIEW, ALTER, ALTER ROUTINE, CREATE, CREATE ROUTINE, CREATE TEMPORARY TABLES, CREATE VIEW, DELETE, DROP, EVENT, INDEX, INSERT, REFERENCES, TRIGGER, UPDATE, LOCK TABLES  ON `aarrstat`.* TO 'aarr'@'localhost' WITH GRANT OPTION;
FLUSH PRIVILEGES;